---
output:
  html_document: 
    css: style.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Time Series and Forecasting


- ***Trend***
  
  Data `time series` yang memiliki observasi membentuk pola cenderung naik atau turun pada periode waktu tertentu.

- ***Cyclic***

  `Cyclic pattern` terjadi jika data `time series` memiliki pola berulang yang tidak tetap dan dipengaruhi oleh siklus bisnis.

- ***Seasonal***

  Efek `Seasonal` terjadi jika data `time series` memiliki pola berulang yang tetap pada periode tertentu.

- ***Smoothing***

  `Smoothing` merupakan transformasi data `time series` yang dapat membantu melihat pola pada data dengan menghapus variasi antar observasi.

- ***Alpha***

  Parameter untuk `smoothing` nilai `error` pada model `exponential smoothing`.
  
- ***Beta***

  Parameter untuk `smoothing` nilai `trend` pada model `exponential smoothing`..
  
- ***Gamma***

  Parameter untuk `smoothing` nilai `seasonal` pada model `exponential smoothing`.

- ***Differencing***

  `Differencing` merupakan transformasi data yang digunakan untuk membuat data `time series` menjadi stasioner.
  
- ***Additive***

  Peningkatan nilai suatu observasi baik pada komponen `trend` ataupun `seasonal` secara konstan.
  
- ***Multiplicative***

  Peningkatan nilai suatu observasi baik pada komponen `trend` ataupun `seasonal` yang semakin membesar.
  
- ***Autocorrelation***

  Hubungan antara suatu variabel dengan dirinya sendiri pada periode waktu yang berbeda.

- ***Stationarity patern***

  Keadaan dimana data `time series` berada di sekitar rata-rata.

- ***Autoregressive model (AR)***

  `Autoregressive model` hampir sama dengan model `linear regression`, namun `predictor` yang digunakan adalah nilai `target variable` itu sendiri pada masa lampau.

- ***Integrated (I)***

  Menjelaskan mengenai berapa kali model melakukan `differencing`.

- ***Moving average (MA)***

  `Moving average` digunakan untuk melakukan `smoothing` terhadap `error.`


